### PR TITLE
732 Update typographic scale

### LINKED ISSUE #719: Headings padding need to be reviewed for linear text, to allow for visual association
For sections of content on a page where the text not contained in a box we need more padding on top of a title than below to aid scannability of the content. At the moment the equal padding makes it very hard to know what content is associated with which title, it also visually makes it hard to scan the sections.

### LINKED ISSUE #732: Improve typographic scale
The currently implemented [typographic scale](https://docs.vanillaframework.io/base/typography/) on Vanilla could do with some improvements, as it was a bit rushed for release of v1.

The initial idea with the current scale was to keep to a strict vertical rhythm, but I don't think this has worked. We should review the font sizes and spacing between elements and update them with values that work well on large to medium to small screens.

It should include:
- h1 to h6 headings
- paragraph
- blockquote
- inline code and code block
- ordered and unordered lists (current spacing is too tight)
- definition lists
- consider margin top of text elements that follow other text elements (e.g. h1/h2/h3/etc that follows paragraph, lists that follow headings or paragraphs, blockquotes that follow headings/paragraphs, etc.)

See also issue #719

### LINKED ISSUE #960: Further amends to Headings vertical rhythm
As proposed by @spencerbygraves:

Adding these for different screen sizes.

**Large:**

- h1 = 48px
- h2 = 36px
- h3 = 28px
- h4 = 24px
- h5 = 20px
- h6 = 16px regular
- p = 16px

afa143fe-0975-11e7-8a8a-903336df61c1

**Medium and small**

h1 = 32px
h2 = 28px
h3 = 24px
h4 = 22px
h5 = 18px
h6 = 16px regular
p = 16px

f4d71cf0-0975-11e7-97d8-03fad151e65d

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

Worked through base components, tweaking spacing to produce consistent visual spacing.

## QA

- Pull code
- Run `gulp jekyll`
- Cross-ref [example](http://127.0.0.1:4000/vanilla-framework/examples/base/typo-scale/) with [spec](https://github.com/vanilla-framework/vanilla-framework/issues/732)  

## Details

Fixes #960,  Fixes #732, Fixes #719, Fixes https://github.com/vanilla-framework/vanilla-docs-theme/issues/25

### CODE REVIEW

**Comment by anthonydillon** [comment]
Good stuff mate! Few things when QA'ing.

## QA issues:
### H1
Expected: `margin-top: 60px`
Actual: `margn-top: 64px` 

### Figcaption, Form label
Expected: `margin-bottom: 16px`
Actual: `margn-top: 14px`

### input[type='checkbox'] + label
Expected: `margin-bottom: 16px`
Actual: `margn-top: 12px`

### H6
Expected: `margin-top: 0`
Actual: `margin-top: 1.5rem`

**Comment by yaili** [comment]
Just to make sure this is not merged until it's been reviewed and tested across devices by design, as per description of next steps in #732. Thanks!

**Comment by anthonydillon** [comment]
Demo: http://barrymcgee.dreamhosters.com/vanilla-framework/examples/base/typo-scale/

**Comment by spencerbygraves** [comment]
See comment here - https://github.com/vanilla-framework/vanilla-framework/issues/960

**Comment by pmatulis** [comment]
I do not see evidence of my [original issue](https://github.com/vanilla-framework/vanilla-docs-theme/issues/25) being fixed. Please advise.

**Comment by barrymcgee** [comment]
@pmatulis See https://github.com/vanilla-framework/vanilla-framework/pull/1095

**Pull request closed without merging**
