### PR TITLE
Standardise spacing

### LINKED ISSUE #728: We should standardise spacing in Vanilla
Inspired by an article shared by @yaili (https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62#.rk9ky220b), we should standardise the spacings in Vanilla for consistency and flexibility.

Currently most spacing in Vanilla is covered by:

* 0 .5rem - 8px
* 0.8125rem - 12px
* 1rem - 16px 
* 1.5rem - 24px

These should be given an appropriate naming convention (t-shirt sizes) and the code refactored accordingly. Any outlying spacing not covered by these values should then be pulled into line.

### PR DESCRIPTION
**Pull request by barrymcgee**
**Note**: This scale needs design sign off.

## Done

Added standardised spacing values with the following scale:

```
$sp-xx-small: 1rem * .25; // 0.25rem
$sp-x-small: 1rem * .5; // 0.5rem
$sp-small: 1rem * .75; // 0.75rem
$sp-medium: 1rem; // 1rem
$sp-large: 1rem * 1.5; // 1.5rem
$sp-x-large: 1rem * 2; // 2rem
$sp-xx-large: 1rem * 2.5; // 2.5rem
$sp-xxx-large: 1rem * 3; // 3rem
```

## QA

- Check code
- Check through patterns to ensure none of them are broken

## Details

Fixes #728

### CODE REVIEW

**Comment by barrymcgee** [comment]
The Percy regressions flagged here are unexpected and seem to be an anomaly. I've reached out to the Percy guys for support.

**Comment by yaili** [comment]
Is it possible to get a demo link for this? Thanks!

**Comment by barrymcgee** [comment]
@yaili This is a code change only, the output should be the exact same as `develop` which you can see by running `gulp jekyll` locally.

**Comment by spencerbygraves** [comment]
This seems to make sense as a scale based on multiples of 4, but I'm not sure it goes far enough. For example, in our Juju work we go as high as 80px vertical spacing on some elements. And I probably wouldn't go below 12px. Would those finer details be added at a theme level?

**Comment by barrymcgee** [comment]
@spencerbygraves Yes - the edge use cases move downstream to either the theme or perhaps even the product codebase itself if the use case cannot be verified across two or more products to justify it's inclusion even at theme level.

**Comment by spencerbygraves** [comment]
@barrymcgee Ok, thanks

**Comment by barrymcgee** [comment]
Tim from Percy has said they are still looking to the visual regression issue.

**Comment by barrymcgee** [comment]
Just to note here - the Percy anomaly was because I failed to interpolate the Sass variables in `calc()` functions - my bad and a great catch by Percy!

**Pull request merged**
