### PR TITLE
add header to p-card

### LINKED ISSUE #1052: Document (and build?) card with heading
# 2. Pattern proposal/amendment

Extension of card pattern to have a heading if needed

## Is this a proposal or an amendment?

- Amendment

## Visual

Design specs: https://github.com/ubuntudesign/vanilla-design/tree/master/Card

## Context

Original proposal: https://github.com/vanilla-framework/vanilla-framework/issues/906
Design issue: https://github.com/ubuntudesign/vanilla-design/issues/11

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* added a header to p-card per the [spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Card/card.md)
* updated the example
* updated the documentation

## QA

1. run locally
2. see the [jekyll example](http://127.0.0.1:4000/vanilla-framework/examples/patterns/card/card/)
3. compare to the spec and [image](https://github.com/ubuntudesign/vanilla-design/blob/master/Card/cards.png)

## Details

Fixes #1052 

## Screenshots

image

### CODE REVIEW

**Comment by pmahnke** [comment]
@yaili I see the spec says 25px for the images, but the example has a 31px one... and the page that brought this up has a 65px one... perhaps we should remove the max-height on the image in the header to be safe?  what do you think?

**Comment by yaili** [comment]
@pmahnke so the height is manually added case by case?

**Comment by barrymcgee** [comment]
Demo: [http://vanilla-framework-1052-add-heading-to-p-card.demo.haus](http://vanilla-framework-1052-add-heading-to-p-card.demo.haus)

**Comment by barrymcgee** [comment]
Demo: http://vanilla-framework-1052-add-heading-to-p-card.demo.haus/vanilla-framework/

**Comment by pmahnke** [comment]
@yaili I just think that we would likely want to break the 32px limit and that would be an overwrite... we could just see how it goes?  what have we done in other situations?

**Comment by yaili** [comment]
We can see how it goes.

- [ ] The header spec has no font size defined, it should not be constrained to 1.5rem as we might want smaller/larger headings for each case
- [ ] Similarly to the other issue, the card padding changes to 21.3px at smaller screens - it should stay the same

**Comment by barrymcgee** [comment]
@yaili As far as I can see, the card padding is 20px through all breakpoints?

**Comment by spencerbygraves** [comment]
@barrymcgee is the demo for this one down?

**Comment by spencerbygraves** [comment]
@WillMoggridge the demo for this is down, could you help please?

Thanks

**Comment by anthonydillon** [comment]
## Demo
http://vanilla-framework-1052-add-heading-to-p-card.demo.haus/vanilla-framework/examples/patterns/card/card/

**Pull request merged**
