### PR TITLE
Add a method of handling form validation for select dropdowns

### PR DESCRIPTION
**Pull request by deadlight**
## Done

Added a way of handling select dropdowns with validation states.
This requires additional markup but is the cleanest option I can find.

## QA

- Pull code
- Run `./run serve --watch`
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/forms/form-validation/
- See the dropdown error state (other states can be seen by changing the parent's class)

## Details

Fixes: #2044

### CODE REVIEW

**Comment by anthonydillon** [comment]
Nice solution. Could you please update the documentation to explain what to do different with select input. 

## QA
- Select inputs are slightly shorter then text inputs so either adjust the top value on the error icon or make the inputs heights uniform

**Comment by anthonydillon** [comment]
Looking good, can you update the documentation please.

**Comment by deadlight** [comment]
@anthonydillon done

**Comment by kwm14** [comment]
Nice @deadlight LGTM 👍 I'm guessing this variation will be used in MAAS? @anthonydillon

**Comment by anthonydillon** [comment]
@kwm14 that's right. It's in MAAS.

**Pull request merged**
