### PR TITLE
Update table component to match spec

### LINKED ISSUE #1306: Table component doesn't match design spec
## Bug

Update table component to match design spec [here](https://github.com/ubuntudesign/vanilla-design/tree/master/Table).

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

Update table component to match spec

## QA

- Pull code
- Run `./run serve --watch`
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/table/
- Verify it matches [the spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Table)

## Details

Fixes #1306

## Screenshots

@kwm14 The trouble with right aligning numerical cells is the disparity with textual header labels on large screens - thoughts?

screen shot 2017-09-28 at 11 35 10

### CODE REVIEW

**Comment by kwm14** [comment]
@barrymcgee can't we just right align the header column associated with the numerical values?

**Comment by barrymcgee** [comment]
@kwm14 Ok, made that change - it now looks like:

screen shot 2017-09-28 at 19 15 47

If you're happy with that, can you update the spec also?

**Comment by kwm14** [comment]
@barrymcgee thanks 👍  I'll update the md file now.

**Comment by Lukewh** [comment]
## QA OK 👍

**Pull request merged**
