### PR TITLE
Widen gutter width to 1/1.618 of column width

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

Increase gutter width to 1/1.618 of column width

## QA

- Pull code
- Run `./run serve --watch`
- Open http://0.0.0.0:8101/vanilla-framework/
- [Add additional steps]

## Details

[List of links to issues/bugs and cards if needed]

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by barrymcgee** [comment]
You can really see the difference in the Percy snapshots where there is now much more whitespace between elements that sit tight to column edges. This is really good work @lyubomir-popov - thank you.

**Comment by barrymcgee** [comment]
@lyubomir-popov I think you should propose this [upstream to Shelves](https://github.com/typeimage/shelves) also

**Comment by lyubomir-popov** [comment]
thanks @barrymcgee - please don't merge yet, @anthonydillon needs to confirm it doesn't break anything on ubuntu.com and other sites.

**Comment by anthonydillon** [comment]
A demo of this branch running on www.ubuntu.com is available here: http://www.ubuntu.com-pr-vanilla-test.run.demo.haus/

**Comment by anthonydillon** [comment]
@lyubomir-popov would you mind adding your max-width proposal to this branch too so its a single review of www.ubunut.com.

**Comment by spencerbygraves** [comment]
We will be having a meeting on Monday 20th to review this.

**Comment by lyubomir-popov** [comment]
@anthonydillon I have updated branch gutter-width to include the max-width proposal. We'll review with @spencerbygraves later today. Side question - is it straightforward to run ubuntu.com on this branch locally?

**Comment by lyubomir-popov** [comment]
@anthonydillon Divider pattern border adjustment due to the wider gutters:
https://github.com/vanilla-framework/vanilla-framework/pull/1437

**Comment by lyubomir-popov** [comment]
We reviewed with @spencerbygraves, things we've noticed:
1. Divider pattern - border needs to be adjusted to sit inside gutter #1437
2. Some patterns that don't use the grid have continue to have narrow gutters:
- Matrix (we have a separate proposal for it, to be discussed with @kwm14)
current:
screen shot 2017-11-20 at 14 48 25

- .p-list.is-split - might benefit from a gutter column-gap: 2rem (rems as it doesn't support % values, so we can't perfectly match the % gutters of the grid)
screen shot 2017-11-20 at 14 42 15


- same patterns seem to have different implementations, some of which don't adhere to the grid - for example cards:
screen shot 2017-11-20 at 14 45 02

compare to:

this screenshot is on the grid, and I've changed the margin-bottom  from 1rem to 2rem to visually match the wider gutter.
screen shot 2017-11-20 at 15 16 37

**Comment by anthonydillon** [comment]
While reviewing Percy there were a number of patterns that have regressions/side effects that need consideration. 

Particularly:
- Notifications
- Text alignment

**Comment by lyubomir-popov** [comment]
@anthonydillon how can I see the side effects? I get a "Forbidden" message when I click on the percy details link.

**Comment by anthonydillon** [comment]
@lyubomir-popov try now, I have made you an owner or the org.

**Comment by lyubomir-popov** [comment]
@kwm14 I've reviewed the regressions and side effects and fixed where necessary. Can you please review and approve?

**Comment by kwm14** [comment]
@lyubomir-popov visual regressions look good 👍  @anthonydillon design looking good I will add 'don't merge' label as I know you wanted to run some more tests as discussed in Standup this morning.

**Pull request merged**
