### PR TITLE
Add social icons to icon set

### LINKED ISSUE #1393: Build social icons and sharing component
## Design spec

- Design and mark down file can be found [here](https://github.com/ubuntudesign/vanilla-design/tree/master/Icons)
    - social-icons and share-buttons
- Original design issue [here](https://github.com/ubuntudesign/vanilla-design/issues/92)

## Build spec

Whoever comes to implement this, please don't forget to consider @bartaz's implementation:

https://github.com/canonical-websites/snapcraft-flask/blob/master/static/sass/_patterns_social-icons.scss

As originally [mentioned here](https://github.com/ubuntudesign/vanilla-design/issues/88).

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

- Add social icons to icon set
- Added docs for all icons

## QA

- Pull code
- Run `./run serve --watch`
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/icons/icons-social/
- Check icons and hover states
- Check docs are accurate

## Details

Fixes #1393

### CODE REVIEW

**Comment by kwm14** [comment]
## Visual review

### Tested in both Chrome and Safari

- [ ] update margin-right on icons to: `1rem`

- [ ] Google+, Twitter and Canonical icons slightly cropped to the right
screen shot 2017-10-27 at 14 11 32

**Comment by anthonydillon** [comment]
## QA
- Replace `no-margin--bottom` with `no-margin--top` in the social icons demo.

**Comment by barrymcgee** [comment]
@kwm14 The icons themselves don't dictate margins - that demo is just using an `.p-inline-list` which dictates the right margin:

screen shot 2017-10-27 at 15 04 34

To change margins here, you'd need to amend the right margins on an inline list?

**Comment by kwm14** [comment]
@barrymcgee thanks for the update. Bug fix looks good 👍 

Ok cool I will look into the **inline-list** component and if it doesn't cause any issues I will raise a bug to update.

**Pull request merged**
