### PR TITLE
1544: Add simple search functionality to docs sidenav

### LINKED ISSUE #1544: Add search functionality to Vanilla docs

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Added a search box to the sidenav in docs that filters the Vanilla patterns
- Updated header nav to match [vanillaframework.io](https://vanillaframework.io/)
- Updated docs to Vanilla 1.6.6 (will be released very soon)

## QA

- Pull code
- Run `cd docs && ./run`
- Open http://0.0.0.0:8104/
- Check that there is a search box in the sidebar navigation
- Check that it filters the results properly (it's just a simple title search, not a content search)

## Details

Fixes #1544

### CODE REVIEW

**Comment by anthonydillon** [comment]
For design:
screenshot-2018-2-7 home documentation

**Comment by Caleb-Ellis** [comment]
screenshot 10

**Comment by kwm14** [comment]
Great job @Caleb-Ellis just a couple of design updates 😉 

## Design review
- [ ] Remove 'Documentation' title as users will know they're in Docs as you've now implemented the navigation from vf.io
- [ ] Rlip 'Version dropdown' and 'Search box' so that search is above sidebar navigation
- [ ] Update placeholder text to say 'Search components'
- [ ] On your screenshot the [x] icon is visible but you haven't searched anything, is that a bug?

### Visual reference
docs-search

**Comment by Caleb-Ellis** [comment]
# Homepage
screenshot 11

# Component page w/ search input
screenshot 12

**Comment by kwm14** [comment]
Beaut 👍  great job!

**Pull request merged**
