### PR TITLE
Adjust spacing between icon and meta item in media object (1666)

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

[List of work items including drive-bys]

## QA

- Pull code
- Run `./run serve --watch`
- Open http://0.0.0.0:8101/vanilla-framework/
- [Add additional steps]

## Details

[List of links to issues/bugs and cards if needed]

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by Caleb-Ellis** [comment]
@kwm14 Did we want meta-list items to have left padding even if there's no icon, like before?
## Old version
screenshot_2

**Comment by lyubomir-popov** [comment]
@Caleb-Ellis I think someone flagged this as a problem, e.g. in Snapcraft where the meta item is a publisher's name. It looked awkward when indented. Is there a place where that indent is meaningful when there's no image?

**Comment by kwm14** [comment]
@Caleb-Ellis @lyubomir-popov I'm not sure now seeing both versions... I agree with @lyubomir-popov that it does look awkward indented without an icon/image, but when you have a mix of items with/without icons it look ok.

## directory.canonical.com
screen shot 2018-04-11 at 14 26 17

**Comment by kwm14** [comment]
@lyubomir-popov that's the word I was thinking of 'keyline' 😄 thanks for updating 👍

**Comment by lyubomir-popov** [comment]
@kwm14 @Caleb-Ellis The pr has been updated, looks like this now:

image

**Comment by kwm14** [comment]
Thanks @lyubomir-popov design looks good 👍

**Pull request merged**
