### PR TITLE
Switch out copy icon for new version

### LINKED ISSUE #1114: Update the copy to clipboard icon
## Is this a proposal or an amendment?

- Amendment

Update the copy to clipboard icon in the [code snippet pattern](https://docs.vanillaframework.io/en/patterns/code-snippet)

## Visual

New icon:
copy-to-clipboard

Dropbox:
https://www.dropbox.com/sh/qavoyn7fgmjkh5j/AADYxKYLIxkgCDcHqrh8RwNwa?dl=0

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

Switched out and added new 'Copy to clipboard' icon on Code Snippet pattern

## QA

- Pull branch
- run `gulp jekyll`
- View http://0.0.0.0:8101/vanilla-framework/examples/patterns/code-snippet/

## Details

Fixes #1114

## Screenshots

screen shot 2017-06-19 at 17 12 39

### CODE REVIEW

**Comment by barrymcgee** [comment]
Demo: http://vanilla-framework-1114-clipboard-icon.demo.haus/vanilla-framework/examples/patterns/code-snippet/

**Comment by spencerbygraves** [comment]
The icon needs a transparent background, which is my mistake. I'll update it.

I'll add the -1 label for me

**Comment by anthonydillon** [comment]
I have tidied up and minified the image to as small as I can:
```svg
<svg viewBox="0 0 80 87" xmlns="http://www.w3.org/2000/svg"><title>Copy to clipboard</title><path d="M20.768411 9c-2.3605569 0-4.2284217.2650655-5.8029606.99893186-1.5745389.73386634-2.8357829 2.06125524-3.581289 3.73894104C9.8931403 17.0932446 10.0522098 21.1966451 10 26.804572v42.3930288c.0522098 5.6079269-.1068597 9.7113275 1.3841614 13.0666991.7455061 1.6776858 2.0067501 3.0028907 3.581289 3.7367571C16.5399893 86.7349345 18.4078541 87 20.768411 87h48.4613839c2.3605658 0 4.230171-.2650655 5.8047098-.998943 1.5745389-.7338664 2.8340337-2.0590713 3.5795397-3.7367571 1.4910211-3.3553716 1.3319516-7.4587833 1.3841614-13.0666991L80 69.1845637V26.8157148l-.0017942-.0111428c-.0522098-5.6079157.1068597-9.7113274-1.3841614-13.0666991-.745506-1.6776858-2.0050008-3.0050747-3.5795397-3.73894104C73.4599659 9.2650655 71.5903607 9 69.2297949 9H20.768411z" fill="#666"/><path d="M21.0862035 13h47.827593c2.0987784 0 3.5628538.282617 4.4837796.7233147.9209346.4406864 1.3188613.9139239 1.6773104 1.7421177.7155615 1.6532713.8730641 5.3926422.9251135 11.0811791v42.8781099c-.0517041 5.7065005-.2082152 9.4534699-.9251135 11.1098462-.3584491.8281938-.7563758 1.2992296-1.6773104 1.739916C72.4766503 82.7151701 71.0125749 83 68.9137965 83h-47.827593c-2.0987695 0-3.5628538-.2848299-4.4837796-.7255164-.9209258-.4406864-1.3188613-.9117222-1.6773104-1.739916C14.209552 78.881285 14.0520405 75.1397237 14 69.4511868V26.5467019c.0520582-5.688537.209552-9.4279078.9251135-11.0811792.3584491-.8281938.7563846-1.3014312 1.6773104-1.7421177.9209258-.4406977 2.3850101-.7233147 4.4837796-.7233147V13z" fill="#FFF"/><path d="M56.990508 9v12.0047484H33V9h7.9987882c0 2.2344898 1.7650687 4.0015828 3.9964658 4.0015828S48.993672 11.2344898 48.993672 9h7.996836z" fill="#666"/><circle fill="#FFF" cx="45" cy="8" r="7"/><path d="M52.9975805 7.99805c0 4.39491-3.6051436 8-7.9987853 8-4.3936416 0-7.9987952-3.60509-7.9987952-8C37 3.60313 40.6051536 0 44.9987952 0c4.3936417 0 7.9987853 3.60313 7.9987853 7.99805zm-3.998418 0c0-2.23228-1.766761-3.99805-4.0003673-3.99805-2.2336062 0-4.0003772 1.76577-4.0003772 3.99805 0 2.23228 1.766771 4 4.0003772 4 2.2336063 0 4.0003673-1.76772 4.0003673-4zM42 36h28v4H42zm0 12h28v4H42zm8 12h20v4H50z" fill="#666"/><path fill="#FFF" d="M0 54h39.6v18H0z"/><path d="M22.0006997 50.0000003s10.6689468 5.131013 19.9993 12.5236419h-.0146258c-9.8416544 7.6286409-19.98537424 12.4776395-19.98537424 12.4776395l.00070003-25.0012814z" fill="#666"/><path fill="#666" d="M0 58h23v10H0z"/></svg>
```

**Comment by spencerbygraves** [comment]
I've updated the icon:

https://www.dropbox.com/sh/qavoyn7fgmjkh5j/AADYxKYLIxkgCDcHqrh8RwNwa?dl=0

**Comment by barrymcgee** [comment]
@spencerbygraves Updated demo: http://vanilla-framework-1114-clipboard-icon.demo.haus/vanilla-framework/examples/patterns/code-snippet/

**Comment by spencerbygraves** [comment]
@barrymcgee thanks

**Pull request merged**
