### PR TITLE
Add form validation pattern

### LINKED ISSUE #797: Update form validation with new designs
# 2. Pattern proposal/amendment

## Is this a proposal or an amendment?

- Amendment to https://docs.vanillaframework.io/base/forms/

## Visual

New design: https://github.com/ubuntudesign/vanilla-design/tree/master/Forms

## Context

Forms

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

- Added form validation pattern

## QA

- Pull code
- Run `gulp jekyll`
- Compare [examples](http://127.0.0.1:4005/vanilla-framework/examples/patterns/form-validation/) to the [design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Forms)

Note: The spec states the icons should be 12px from the bottom - in practice, this is not enough:

screen shot 2017-02-23 at 10 22 27

As they also need to work `<textarea>` elements also, I have vertically centred the icons instead.

## Details

Fixes #797

### CODE REVIEW

**Comment by anthonydillon** [comment]
@barrymcgee whats the plan for this PR?

**Comment by barrymcgee** [comment]
@anthonydillon It's waiting on your re-review after my last change

**Comment by anthonydillon** [comment]
I don't like the requirement of more markup here. Couldn't this be achieved using a background image on the input?

The only reason to use an `:after` would be if it was interactive.

**Comment by richmccartney** [comment]
@anthonydillon @barrymcgee can I suggest we look at what I have done for forms on MAAS. We have the form validation including icons. The scss can be found here https://github.com/ubuntudesign/maas-gui-vanilla-theme/blob/master/scss/_components.forms.scss

**Comment by barrymcgee** [comment]
@richmccartney What is the benefit/value of your approach over this approach?

**Comment by anthonydillon** [comment]
@richmccartney I don't see any validation in your code?

**Pull request merged**
