### PR TITLE
Spacing overhaul

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

new settings for more harmonious typographic spacing
refactor typography file so it is more manageable
fix affected patterns

add .has-eyebrow utility
add u-min-margin--bottom utility

## QA

- Pull code
- Run `./run serve --watch`
- QA code and Persy screenshots for regressions

### CODE REVIEW

**Comment by kwm14** [comment]
Thanks @lyubomir-popov will review Percy now 😄

**Comment by kwm14** [comment]
## Design review
Decent work @lyubomir-popov couple of comments regarding spacing on some components 😉 

**/vanilla-framework/examples/patterns/notifications**
- top spacing on update looks tighter compared to bottom spacing. Should spacing be equal top and bottom now?

screenshot 2019-01-16 at 12 48 08

**/vanilla-framework/examples/patterns/heading-icon/heading-icon**
- heading icon title aligned to top rather than center aligned to icon

screenshot 2019-01-16 at 12 50 59

**/vanilla-framework/examples/patterns/lists/lists-stepped-detailed**
- stepped title slightly out of alignment with accommodating copy to the right

screenshot 2019-01-16 at 12 53 23

**/vanilla-framework/examples/patterns/accordion**
- open row text aligned to top rather than center aligned to field

screenshot 2019-01-16 at 12 55 18

**Comment by lyubomir-popov** [comment]
Good catches @kwm14, thanks. Working through those now, I'll push an update shortly.

**Comment by lyubomir-popov** [comment]
@kwm14 In the case of the stepped list, the h3 actually sits on the same baseline as the p. This is intended I would say, as it allows h3, h4, h5, h6, and p to line up properly:

image

image

**Comment by lyubomir-popov** [comment]
@kwm14 would iut be an option to change the heading-icon size from 3rem to 2.5rem? Given the tighter spacing, the icon is simply too big now. Comparison:

Icon size 2.5rem:

image

Icon size 3 rem:
image

**Comment by lyubomir-popov** [comment]
if we were to change it, it would become consistent with the stepped list circles size:
image

**Comment by kwm14** [comment]
> @kwm14 would iut be an option to change the heading-icon size from 3rem to 2.5rem? Given the tighter spacing, the icon is simply too big now. Comparison:
> 
> Icon size 2.5rem:
> 
> image

Happy to update heading-icon size to `2.5rem` 😄 looks much better and it's better to update the icon size rather than re-adjusting vertical spacing across the board.

**Comment by lyubomir-popov** [comment]
@kwm14 great! I'll adjust it as part of this pr as it is part of the solution to to the issue.

**Comment by kwm14** [comment]
> @kwm14 In the case of the stepped list, the h3 actually sits on the same baseline as the p. This is intended I would say, as it allows h3, h4, h5, h6, and p to line up properly:
> 
> image
> image
> 
> image

@lyubomir-popov Oh I see. I couldn't see that on the Percy visual diff, applying the baseline guide as you have in your example looks ok.

But visually headings look out of alignment next to button 😮

**Comment by lyubomir-popov** [comment]
@kwm14 since the headings snap t oa baseline grid, it'a a choice of +/- .5rem. I think lining it with the baseline of the text looks slightly better. Comparison:

image

**Comment by kwm14** [comment]
> @kwm14 since the headings snap t oa baseline grid, it'a a choice of +/- .5rem. I think lining it with the baseline of the text looks slightly better. Comparison:
> 
> image

@lyubomir-popov Looking at it individually rather than a page full of all instances of the component use cases, it does look better. Good to go with this 👍

**Comment by lyubomir-popov** [comment]
I've pushed my final fixes for these, please review again.

**Comment by kwm14** [comment]
## Design review
Updates to components looking good @lyubomir-popov 👍 just a couple of comments on new example pages you've created. This might just be Percy playing up but wanted to double check before approving 😄 

**/vanilla-framework/examples/templates/heading-button-cta**
- Button paddings / margins look broken on 'get started' buttons?

screenshot 2019-01-17 at 12 33 47

**/vanilla-framework/examples/templates/typographic-spacing**
- Titles not wrapping inside cards? As seen in your example below

screenshot 2019-01-17 at 12 36 11

**Comment by lyubomir-popov** [comment]
@kwm14 thanks for re-reviewing, both seem fine to me: 

/vanilla-framework/examples/templates/heading-button-cta :
this is a percy issue, the actual example looks fine - https://vanilla-framework-vanilla-framework-pr-2107.run.demo.haus/vanilla-framework/examples/templates/heading-button-cta/

/vanilla-framework/examples/templates/typographic-spacing :
lack of wrapping is not an issue here. the goal of this is to show spacing between elements. 
Also please note the wrapping happens at a very low resolution. On a normal laptop they shouldn't wrap.

**Comment by kwm14** [comment]
> @kwm14 thanks for re-reviewing, both seem fine to me:
> 
> /vanilla-framework/examples/templates/heading-button-cta :
> this is a percy issue, the actual example looks fine - https://vanilla-framework-vanilla-framework-pr-2107.run.demo.haus/vanilla-framework/examples/templates/heading-button-cta/
> 

@lyubomir-popov yep percy issue. demo looks good 💯 

> /vanilla-framework/examples/templates/typographic-spacing :
> lack of wrapping is not an issue here. the goal of this is to show spacing between elements.
> Also please note the wrapping happens at a very low resolution. On a normal laptop they shouldn't wrap.

Ok great 👍

**Comment by pmahnke** [comment]
@lyubomir-popov, I really don't like these huge PRs, it is really hard to understand what's changing and test them and see them, etc... If they all need to go live together, let's create a branch and do a PR for each thing moving.  Even if you develop them in one go, you can break the changes into multiple groups.

**Comment by lyubomir-popov** [comment]
@pmahnke I will break it down.

**Comment by lyubomir-popov** [comment]
Closing this as it will be broken down into several smaller prs.

**Comment by lyubomir-popov** [comment]
I've made a new pr with the most essential parts of this, and left the large refactor for a separate pr: https://github.com/vanilla-framework/vanilla-framework/pull/2117

**Comment by lyubomir-popov** [comment]
@pmahnke I've extracted the core of this pr: https://github.com/vanilla-framework/vanilla-framework/pull/2117

The [markup](https://github.com/vanilla-framework/vanilla-framework/pull/2117/files#diff-1015681d8bef3e0a288bfdd5bd407caf) is still a large file, but it is just a more extensive test case to show how the changes affect various combinations. The rest is as small as I could make it.

**Pull request closed without merging**
