### PR TITLE
Update mobile nav to use dropdowns for About and Patterns in docs

### LINKED ISSUE #1948: Update docs mobile menu on vanillaframework.io
## Context

Currently we don't have a mobile specific solution for Vanilla docs, it simply just scales and components respond accordingly. With the help of the UX'ers I've created a mobile solution which will help users.
- Design issue [here](https://github.com/ubuntudesign/vanilla-squad/issues/318) for reference
- Move 'Patterns' to top navigation and add up/down chevrons similarly seen on https://mongoose.ubuntu.com/

## Visual updated
vanilla-docs-menu-008

## Visual current
vanilla-example

### PR DESCRIPTION
**Pull request by deadlight**
## Done

New styling for main nav and sidebar "component" nav at small viewports

## QA

- Pull code
- `cd docs`
- Run `./run`
- Open http://0.0.0.0:8104/
- Resize the viewport to small size
- Check the new dropdown-style toggles for the two navs and compare to the [design](https://github.com/vanilla-framework/vanilla-framework/issues/1948)

## Details
Fixes #1948

### CODE REVIEW

**Comment by kwm14** [comment]
## Design review
Looking super nice @deadlight but 'Patterns' dropdown is broken in navigation 😢 

- [ ] click 'Patterns' and it serves squashed hamburger icon and no menu items

screenshot 2019-03-06 at 10 07 59

**Comment by deadlight** [comment]
@kwm14 I can't replicate this, maybe there's a caching issue?

**Comment by kwm14** [comment]
@deadlight correct it was a caching issue and now I can see the dropdown and menu items 😄 

But...

- [ ] global navigation menu items are offset to the right?

**Updated**
screenshot 2019-03-06 at 10 30 51

**Current**
screenshot 2019-03-06 at 10 31 02

**Comment by deadlight** [comment]
@kwm14 fixed (well there's maybe a pixel or two difference but it looks the same)

**Comment by kwm14** [comment]
Nice work @deadlight LGTM 👍

**Pull request merged**
