### PR TITLE
Add visual :focus state to form elements

### LINKED ISSUE #1366: Add visual focus to form elements
Implement the :focus requirements as set out in [design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Focus%20state)

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

[List of work items including drive-bys]

## QA

- Pull code
- Run `./run serve --watch`
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/forms/form/
- Tab through the form

## Details

Fixes #1366

### CODE REVIEW

**Comment by kwm14** [comment]
@barrymcgee when tabbing onto the checkbox, are we able to have the focus state wrap around the component rather than the container?

### Current result
screen shot 2017-10-04 at 17 56 11

### Expected result
screen shot 2017-10-04 at 17 57 57

**Comment by kwm14** [comment]
Looking good to me 👍

**Comment by anthonydillon** [comment]
Input type file is missing focus styling: http://vanilla-framework-pr-1367.run.demo.haus/vanilla-framework/examples/base/forms/form/

**Comment by anthonydillon** [comment]
http://vanilla-framework-pr-1367.run.demo.haus/vanilla-framework/examples/base/forms/checkboxes/ has misaligned checkboxes

**Comment by anthonydillon** [comment]
Are circular instead of a square: https://vanilla-framework.github.io/vanilla-framework/examples/base/forms/checkboxes/

**Comment by anthonydillon** [comment]
@barrymcgee Fixed up my comments. Can you take a look and merge if your happy.

**Pull request merged**
