### PR TITLE
1459: Update header navigation to new design spec

### LINKED ISSUE #1459: Update global navigation to match new design spec
## Process

Navigation pattern needs to show current highlighted page and rollover state, I've updated the design spec to allow for this.

-  Original design issue raised [here](https://github.com/ubuntudesign/vanilla-design/issues/50)
-  Add hover and selected to current global navigation

## Design spec
- Updated design spec can be found here: https://github.com/ubuntudesign/vanilla-design/tree/master/Navigation

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Updated header navigation to reflect [new design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Navigation)
- Updated example to show selected state, and added aria tags

## QA

- Pull code
- Run `./run serve --watch`
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/default/
- Check that it follows the [new design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Navigation)

## Details

Fixes #1459

### CODE REVIEW

**Comment by kwm14** [comment]
Design 👍

**Comment by Lukewh** [comment]
With the bottom border the overall height of the heading becomes 49px, is this expected? Should the 48px in the spec include the bottom border?

**Comment by Caleb-Ellis** [comment]
@Lukewh You're right, 48px including border. It should be fixed now :eggplant:

**Comment by Caleb-Ellis** [comment]
@Lukewh The more you know! Turns out you don't need aria-selected for links either, just for tabs https://www.stefanjudis.com/blog/aria-selected-and-when-to-use-it/

**Pull request merged**
