### PR TITLE
Update the buttons to match the design spec

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Updated the base and neutral button property values to match the [design spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Buttons/buttons.md).

## QA
- Pull down code
- Run `gulp jekyll`
- Check the following patterns match the spec:
  - Base - http://127.0.0.1:4321/vanilla-framework/examples/patterns/buttons/base/
  - Neutral - http://127.0.0.1:4321/vanilla-framework/examples/patterns/buttons/neutral/
- Check the code is ok

## Details
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/916

### CODE REVIEW

**Comment by barrymcgee** [comment]
@anthonydillon The build failed here due to invalid Scss?

**Comment by anthonydillon** [comment]
My bad, should be fixed now. Ready for review.

**Comment by barrymcgee** [comment]
The padding on all buttons is 11px but should be 12px?

screen shot 2017-03-06 at 17 07 30

**Comment by anthonydillon** [comment]
Great spot @barrymcgee, updated.

**Pull request merged**
