### PR TITLE
Form box styling demo

### PR DESCRIPTION
**Pull request by kwm14**
## Done
Created a demo to show current and proposed form styling.
- Question in mind do we need inner-shadow on forms
- Added to both white and grey backgrounds to test contrast and accessibility

## QA

- Pull code
- Run `./run serve --watch`
- Open http://0.0.0.0:8101/vanilla-framework/examples/templates/box-shadow-on-forms/
- Compare current and proposed examples

## Details
Related issue of discussion https://github.com/ubuntudesign/vanilla-design/issues/319

### CODE REVIEW

**Comment by kwm14** [comment]
@clagom @spencerbygraves demo updated based on feedback convo 👍

**Comment by kwm14** [comment]
@clagom @spencerbygraves Ok great 👍 

Just to clarify we're moving forward with `Proposed styling` updates but keeping current border styling of `border: 1px solid #999`?

**Comment by clagom** [comment]
> @clagom @spencerbygraves Ok great 👍
> 
> Just to clarify we're moving forward with `Proposed styling` updates but keeping current border styling of `border: 1px solid #999`?

Yes, sounds good to me!

**Comment by kwm14** [comment]
Closing demo as this has been fixed up in a new PR and merged: https://github.com/vanilla-framework/vanilla-framework/pull/2071 👍

**Pull request closed without merging**
