### PR TITLE
Dockerfile for docs

### PR DESCRIPTION
**Pull request by WillMoggridge**
This should be merged after #1493 

## Done

Add a docker image for the docs app

## QA

- Pull code
- Install latest documentation-builder (`snap install documentation-builder`)
- `yarn run build-docs`
- `cd docs`
- `docker build . -t vanilla-docs --build-arg COMMIT_ID=$(git rev-parse HEAD)`
- `docker run --rm -p 8080:80 vanilla-docs`
- Visit http://localhost:8080/ and it should look beautiful!

### CODE REVIEW

**Comment by nottrobin** [comment]
> ./run exec yarn run build-docs

Why isn't there a native ./run command for this?

**Comment by nottrobin** [comment]
``` bash
$ ./run exec yarn run build-docs

yarn run v1.2.1
$ documentation-builder --base-directory docs --output-path docs/templates --template-path docs/template.html --tag-manager-code 'GTM-K92JCQ' --no-link-extensions --force
/bin/sh: 1: documentation-builder: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I get this initially. This is because the `./run exec` command doesn't check for and install dependencies first. Which highlights the need for `build-docs` to have its own native endpoint.

**Comment by nottrobin** [comment]
Givan that the Dockerfile is in the `docs/` folder, which seems like a good idea to me, I expected to be able to do:

``` bash
docker build docs -t vanilla-docs --build-arg COMMIT_ID=`git rev-parse HEAD`
```

But then I get:

``` bash
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

Was there a reason why you put the `requirements.txt` at the top level instead of inside the `docs/` folder?

**Comment by WillMoggridge** [comment]
> Why isn't there a native ./run command for this?
I am working to create one in #1416. I wanted to move the other items along while that gets created.

> Was there a reason why you put the `requirements.txt` at the top level instead of inside the `docs/` folder?
This is because the ./run command currently looks for it in the root (until the update) but I do think it would be better in the docs folder as well.

**Comment by nottrobin** [comment]
> This is because the ./run command currently looks for it in the root (until the update) but I do think it would be better in the docs folder as well.

At the moment, the run script doesn't really help you run the docs flask app at all, so could you just move the `requirements.txt` file to where you think it should live and then craft QA steps independently of `./run` until `./run` supports it?

**Comment by WillMoggridge** [comment]
Yeah sure, I will update this shortly.

**Pull request merged**
