### PR TITLE
Update Vanilla colors

### LINKED ISSUE #852: Update Vanilla colours to new agreed palette
# 2. Pattern proposal/amendment

## Is this a proposal or an amendment?

- Amendment: Colors

The following colours have been updated to align with Suru, agreed the Vanilla sprint:
- Text color ($color-dark) from 333333 to 111111
- Positive color ($color-positive) from 0f8420 to 0e8420
- Negative color ($color-negative) from d73024 to c7162b
- Information color ($color-information) from 007aa6 to 335280 - **this means $color-information variable cannot be used for links, see next point**
- Link color (**new**) ($color-link) to be 007aa6

## Visual

Design spec: https://github.com/ubuntudesign/vanilla-design/tree/master/Color

## Context

Used everywhere.

If accepted, this item should have Priority: High.

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

Updated Vanilla color variables and docs

## QA

Sanity check code

## Details

Fixes #852

### CODE REVIEW

**Comment by anthonydillon** [comment]
@barrymcgee please confirm Percy and land.

**Comment by barrymcgee** [comment]
@anthonydillon The reviewer should confirm Percy...

**Comment by anthonydillon** [comment]
Ah, good to know. Will check first thing.

**Comment by anthonydillon** [comment]
I get a "Forbidden" error. Do you need to add us to the new
vanilla-framework.

**Comment by barrymcgee** [comment]
@anthonydillon Have re-sent your invite

**Pull request merged**
