### PR TITLE
Remove the base font size change on small screens

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Set the base font size to always be the font-base-size across all breakpoints.

## QA
- I believe this review is just a code review
- Then check the percy output to see if anything has broken

## Details
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1053

### CODE REVIEW

**Comment by barrymcgee** [comment]
@anthonydillon This change will also need to account for all those instances where different rem values have been specced between breakpoints to keep a pixel value consistent.

**Comment by anthonydillon** [comment]
@barrymcgee thanks, removed all medium breakpoint overrides.

**Comment by anthonydillon** [comment]
@barrymcgee all changes in percy are expected for me. Design can you please review: https://percy.io/vanilla-framework/vanilla-framework/builds/218148

**Comment by anthonydillon** [comment]
@yaili do you mind taking a look at the demo: http://www.ubuntu.com-global-nav.demo.haus

**Pull request merged**
