### PR TITLE
Combine brochure theme list patterns

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Ported over the two list patterns from brochure theme.

## QA

- Pull code
- Run `./run serve --watch`
- Open http://0.0.0.0:8101/vanilla-framework/
- Check http://0.0.0.0:8101/examples/patterns/lists/lists-ticked/
- Check http://0.0.0.0:8101/examples/patterns/lists/split-list/

## Details
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1210

### CODE REVIEW

**Comment by yaili** [comment]
Not an issue with the pattern itself, but can this be listed as: List / Split in the examples, and similarly in the documentation. Also, let's not use title case.

**Comment by kwm14** [comment]
@barrymcgee pattern looks good but agree with @yaili can 'Split-list' example name be changed so it's similar to current list variants.

### Current result
Split List

### Expected result
Lists / Split

**Comment by anthonydillon** [comment]
@kwm14 that was done: https://github.com/vanilla-framework/vanilla-framework/pull/1252/commits/88614584b4fc8cec74884026438cd241fe391833#diff-16e45c1ff771282a2fbd0296e27ab783R4

**Comment by kwm14** [comment]
@anthonydillon great. thanks

**Pull request merged**
